### ISSUE TITLE
[코드리뷰] 부동산 기간 계산 로직.

### ISSUE THREAD

**Issue by shininghyunho** [krescere/jipsayo-frontend#1]
https://github.com/krescere/jipsayo-frontend/blob/7871bdb8109886bb654091837221df314c78cbae/src/utils/functions/house.ts#L31
```
    if (yearMoney <= target) {  //  [0년 12개월 -> 1년 0개월]이 맞을거같습니다.
```

https://github.com/krescere/jipsayo-frontend/blob/7871bdb8109886bb654091837221df314c78cbae/src/utils/functions/house.ts#L37
```
      month = Math.floor(target / nextSaving); // 돈이 모자르면 다음달까지 모아야할거같습니다.
```

**Comment by jinhwansuh** [comment]
```
    month = Math.floor(target / nextSaving); // 돈이 모자르면 다음달까지 모아야할거같습니다.
```

이 부분은 올림을 말씀하시는거죠?

**Comment by shininghyunho** [comment]
맞습니다!

**Comment by shininghyunho** [comment]
> ```
>     month = Math.floor(target / nextSaving); // 돈이 모자르면 다음달까지 모아야할거같습니다.
> ```
> 
> 이 부분은 올림을 말씀하시는거죠?

맞습니다!!
